### ISSUE TITLE
Sender → Email: Проблема при указании нескольких почтовых ящиков

### ISSUE THREAD

**Issue by deversjkee** [DivanDesign/MODXEvo.snippet.ddSendFeedback#2]
ddSendFeedback/src/Sender/Email/Sender.php → 16 строка

		//Comma separated string support
		if (!is_array($this->to)){
			$this->to = explode(',', $this->to);
		}

При получении списка почты куда отправлять, строка со всеми почтовыми ящиками становится элементом массива с индексом 0, однако проверка в обозначенном выше файле проверяет не нулевой элемент а весь массив, что приводит к ошибке. Поправить.

Пример: 

```Array
(
    [email] => Array
        (
            [to] => Array
                (
                    [0] => ehot@divandesign.ru,office@klyuchi74.ru,century@live.ru,info@klyuchi74.ru,shakeshead+ww46hotyflyw20etw09w@boards.trello.com,marketing.o.k@yandex.ru
                )

            [subject] => Заявка на пробное занятие
            [from] => info@klyuchi74.ru
            [tpl] => mail_testClassRequest
        )

)```

**Comment by Ronef** [comment]
You must set parameter as comma separated string in this case, not as an array:
```json
&senders=`{
	"email": {
		"to": "info@divandesign.biz,info@divandesign.ru",
		"tpl": "general_letters_feedbackToEmail"
	}
}`.
```

Or as an array:
```json
&senders=`{
	"email": {
		"to": [
			"info@divandesign.biz",
			"info@divandesign.ru"
		],
		"tpl": "general_letters_feedbackToEmail"
	}
}`.
```
