### ISSUE TITLE
Общее → Параметр «$result_show»: Необходимо переделать

### ISSUE THREAD

**Issue by Tornek** [DivanDesign/MODXEvo.snippet.ddSendFeedback#3]
сейчас он работает если параметр есть то не выводим, если нет то выводим результат. По идеи в него нужно передавать boolean значение  и от него плясать, а если он не указан то дефолтно присваивать true.

**Comment by Ronef** [comment]
Вообще надо удалить этот параметр, надо логику вызовов менять, вместо костыльных параметров.
